version: 2.0

jobs:
    build:
        docker:
            - image: circleci/openjdk:8-jdk
        working_directory: ~/repo
        environment:
            JVM_OPTS: -Xmx3200m
            TERM: dumb
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v4-cache-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
                    - v4-cache-
            - run:
                name: Download dependencies
                command: ./gradlew downloadDependencies --no-daemon
            - save_cache:
                paths:
                    - ~/.m2
                    - ~/.gradle
                key: v4-cache-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - run:
                name: Run tests
                command: ./gradlew test --no-daemon
            - run:
                name: Save reports
                command: |
                    mkdir -p ~/results
                    mkdir -p ~/reports
                    find . -type f -regex "./build/test-results/.*xml" -exec cp {} ~/results \;
                    cp -r build/reports/tests/test/* ~/reports
                when: always
            - store_test_results:
                path: ~/results
            - store_artifacts:
                path: ~/reports
    publish:
        docker:
            - image: circleci/openjdk:8-jdk
        working_directory: ~/repo
        environment:
            JVM_OPTS: -Xmx3200m
            TERM: dumb
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v4-cache-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
                    - v4-cache-
            - run:
                name: Assemble artefacts
                command:
                    ./gradlew assemble --no-daemon
            - setup_remote_docker:
                docker_layer_caching: true
            - run:
                name: Build Docker image
                command: |
                    docker build . -t adarshr/adarshr.com
            - run:
                name: Publish Docker image
                command: |
                    docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
                    docker push adarshr/adarshr.com

workflows:
    version: 2
    build-and-publish:
        jobs:
            - build
            - publish:
                requires:
                    - build
                filters:
                    branches:
                        only: master

